export const products = [
  {
    id: 1,
    name: "Cera Spider para Cabello",
    desc: "Fijación extrema y acabado natural.",
    brand: "Spider Wax",
    price: "S/25",
    img: "https://http2.mlstatic.com/D_NQ_NP_949077-MLM49776359742_042022-O-cera-para-cabello-tipo-spider-telarana-wax-s1-150ml-nishman.webp",
    btn: "Pedir por WhatsApp",
    link: "https://wa.me/+51933738449",
  },
  {
    id: 2,
    name: "Aceite para Barba",
    desc: "Hidratación y brillo para tu barba.",
    brand: "Gold Beard",
    price: "S/30",
    img: "https://charlemagne-premium.com/cdn/shop/files/Image9_USP_1.webp?v=1761821991&width=1946",
    btn: "Pedir por WhatsApp",
    link: "https://wa.me/+51933738449",
  },
  {
    id: 3,
    name: "Shampoo Premium",
    desc: "Limpieza profunda y frescura duradera.",
    brand: "Urban Men",
    price: "S/35",
    img: "https://lechepalpelo.com/cdn/shop/products/Relleno_proteinico.jpg?v=1739322022&width=1200",
    btn: "Pedir por WhatsApp",
    link: "https://wa.me/+51933738449",
  },
  {
    id: 4,
    name: "Cera Mate",
    desc: "Look natural sin brillo.",
    brand: "MatteFix",
    price: "S/28",
    img: "https://thebarberia.com/storage/product/vVaCQ28FfLqO0odeQMTtO2KNFhLKXHkewsSLhpiG.png",
    btn: "Pedir por WhatsApp",
    link: "https://wa.me/+51933738449",
  },
];
